# Site settings
title: Matt Stevens
email: coopermayne@gmail.com
description: Location Manager & Scout
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author:
street_address: 1234 Somewhere Road
city: Nashville
state: TN
zip_code: 55555
country: United States of America
phone: (716) 555-5555

icon: fa-male # Font Awesome class for your site's icon

# Social settings
facebook_url:
github_url:
gitlab_url: https://gitlab.com/u/andrewbanchich
googleplus_url: https://plus.google.com/u/0/+AndrewBanchich
instagram_url: asdf
linkedin_url: https://www.linkedin.com/in/andrew-banchich-a4ba1195
pinterest_url: asdf
slack_url:
twitter_url: https://twitter.com/andrewbanchich

# Build settings
markdown: kramdown
